package json

import "testing"

func TestStripComments(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"no comments", `{"a": 1}`, `{"a": 1}`},
		{"line comment", "{\"a\": 1 // hi\n}", "{\"a\": 1 \n}"},
		{"block comment", `{"a": /* x */ 1}`, `{"a":  1}`},
		{"multiline block", "{\"a\": /* line1\nline2 */ 1}", "{\"a\":  1}"},
		{"slashes in string", `{"url": "http://example.com"}`, `{"url": "http://example.com"}`},
		{"block markers in string", `{"s": "/* not a comment */"}`, `{"s": "/* not a comment */"}`},
	}
	for _, tc := range cases {
		if got := string(StripComments([]byte(tc.in))); got != tc.want {
			t.Errorf("%s: StripComments(%q) = %q, want %q", tc.name, tc.in, got, tc.want)
		}
	}
}

// TestParseObjectConfigWithComments verifies the exact shape generated by
// `imge new object` parses: a commented-out example component inside the
// components array, which should strip to an empty object.
func TestParseObjectConfigWithComments(t *testing.T) {
	data := []byte(`{
  "name": "player",
  "depth": 0,
  "ui": false,
  "tags": [],
  "components": [
    // { "kind": "Enemy", "name": "brain", "args": { "speed": 100 } }
  ]
}`)
	cfg, err := ParseObjectConfig(data)
	if err != nil {
		t.Fatalf("ParseObjectConfig with comments: %v", err)
	}
	if cfg.Name != "player" {
		t.Errorf("Name = %q, want %q", cfg.Name, "player")
	}
	if len(cfg.Components) != 0 {
		t.Errorf("Components = %d, want 0", len(cfg.Components))
	}
}
