name: Release IMGE CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build IMGE CLI
      run: |
        go build -o imge_linux_amd64 ./cmd/imge
        mkdir -p dist
        mv imge_linux_amd64 dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/imge_linux_amd64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}